hmc.java.versions=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.6-7/x64/bin/java
hmc.gamedir=/home/runner/work/ArsAddonBuilder/ArsAddonBuilder/run
hmc.offline=true
hmc.rethrow.launch.exceptions=true
hmc.exit.on.failed.command=true
hmc.assets.dummy=true
