# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=1.21.1
short_mc_version=1.21
minecraft_version_range=[1.21,1.21.1)
neo_version=21.1.115
neo_version_range=[21.1.115,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Mod Properties
mod_id=doc_exporter
mod_name=Doc Exporter
mod_license=MIT
mod_version=0.0.4
mod_group_id=dev.qther
mod_authors=Qther
mod_description=Contains a game test that exports docs for mc-runtime-test

# Dependencies
# See https://maven.blamejared.com/com/hollingsworth/ars_nouveau/ars_nouveau-1.21.1/
ars_version=5.7.1.1026
nuggets_version=1.0.4.35
gecko_version=4.6.6

# See https://maven.blamejared.com/mezz/jei/
jei_version=19.21.0.247
curios_version=9.0.12