name: Build Repositories

on:
  workflow_dispatch:

env:
  JAVA_VERSION: 17

permissions:
  contents: write

jobs:
  find:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
      matrix: ${{ steps.filter.outputs.changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: json
          base: ${{ github.ref }}
          filters: |
            changed:
              - 'projects/*.json'
  build:
    runs-on: ubuntu-latest
    needs: find
    if: ${{ needs.find.outputs.changed == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(needs.find.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: info
        run: |
          echo "MODULE=$(jq -c . < ${{ matrix.file }})" >> $GITHUB_OUTPUT
          echo "DIR=$(basename ${{ matrix.file }})" >> $GITHUB_OUTPUT
      - run: |
          mkdir -p build/${{ steps.info.outputs.DIR }}
      - uses: actions/checkout@v4
        name: Checkout module
        with:
          repository: ${{ fromJson(steps.info.outputs.MODULE).repo }}
          ref: ${{ fromJson(steps.info.outputs.MODULE).branch }}
          path: build/${{ steps.info.outputs.DIR }}
      - name: Setup gradle
        shell: bash
        env:
          DIRECTORY: build/${{ steps.info.outputs.DIR }}
        run: |
          chmod +x $DIRECTORY/gradlew
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: gradle
      - shell: bash
        run: |
          mkdir -p ~/.gradle/caches/fabric-loom/assets
      - name: retry action
        uses: Wandalen/wretry.action@v3.5.0
        with:
          attempt_limit: 3
          attempt_delay: 2000
          action: gradle/gradle-build-action@v2
          with: |
            arguments: clean runData
            build-root-directory: build/${{ steps.info.outputs.DIR }}
      - name: Action - rsync
        uses: up9cloud/action-rsync@v1.4
        env:
          MODE: local
          SOURCE: "build/${{ steps.info.outputs.DIR }}/src/main/resources/ build/${{ steps.info.outputs.DIR }}/src/generated/"
          TARGET: resources/${{ steps.info.outputs.DIR }}
          VERBOSE: true
          PRE_SCRIPT: |
            echo start at:
            date -u
          POST_SCRIPT: "echo done at: && date -u"
      - id: find
        shell: bash
        env:
          PROJECT: ${{ steps.info.outputs.DIR }}
        run: echo "project_hash=$(git ls-tree --object-only HEAD $PROJECT)" >> "$GITHUB_OUTPUT"
      - uses: Jarva/git-commit-push@main
        with:
          pull: true
          commit_message: "feat: update ${{ matrix.file }} to ${{ steps.find.outputs.project_hash }}"
