name: Build Repositories

on:
  workflow_dispatch:

env:
  JAVA_VERSION: 17

permissions:
  contents: write

jobs:
  find:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup submodules
        shell: bash
        run: |
          git submodule update --init --remote --recursive
      - id: find
        shell: bash
        run: echo "matrix=$(find . -type d -not -path "." -exec test -e '{}/.git' ';' -print -prune | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-latest
    needs: find
    strategy:
      matrix:
        dir: ${{ needs.find.outputs.matrx }}    
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"