name: Build Repositories

on:
  workflow_dispatch:

env:
  JAVA_VERSION: 17

permissions:
  contents: write

jobs:
  find:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup submodules
        shell: bash
        run: |
          git submodule update --init --remote --recursive
      - id: find
        shell: bash
        run: echo "matrix=$(find . -type d -not -path "." -exec test -e '{}/.git' ';' -exec basename {} \; -prune | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-latest
    needs: find
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJSON(needs.find.outputs.matrix) }}    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup submodules
        shell: bash
        env:
          DIRECTORY: ${{ matrix.dir }}
        run: |
          git submodule update --init --remote --recursive
          chmod +x $DIRECTORY/gradlew
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
      - shell: bash
        run: |
          mkdir -p ~/.gradle/caches/fabric-loom/assets
      - name: retry action
        uses: Wandalen/wretry.action@v3.5.0
        with:
          attempt_limit: 3
          attempt_delay: 2000
          action: gradle/gradle-build-action@v2
          with: |
            arguments: clean runData
            build-root-directory: ${{ matrix.dir }}
      - name: Action - rsync
        uses: up9cloud/action-rsync@v1.4
        env:
          MODE: local
          SOURCE: ${{ matrix.dir }}/src/main/resources/
          TARGET: resources/${{ matrix.dir }}
          VERBOSE: true
          PRE_SCRIPT: |
            echo start at:
            date -u
          POST_SCRIPT: "echo done at: && date -u"
      - name: Action - rsync
        uses: up9cloud/action-rsync@v1.4
        env:
          MODE: local
          SOURCE: ${{ matrix.dir }}/src/generated/
          TARGET: resources/${{ matrix.dir }}
          VERBOSE: true
          PRE_SCRIPT: |
            echo start at:
            date -u
          POST_SCRIPT: "echo done at: && date -u"
      - id: find
        shell: bash
        env:
          PROJECT: ${{ matrix.dir }}
        run: echo "project_hash=$(git ls-tree --object-only HEAD $PROJECT)" >> "$GITHUB_OUTPUT"
      - uses: Jarva/git-commit-push@main
        with:
          pull: true
          commit_message: "feat: update ${{ matrix.dir }} to ${{ steps.find.outputs.project_hash }}"
