name: Build Repositories

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/**'

env:
  JAVA_VERSION: 21
  ARS_URL: https://modmaven.dev/com/hollingsworth/ars_nouveau/ars_nouveau-1.21.1/5.7.1.1026/ars_nouveau-1.21.1-5.7.1.1026-all.jar
  CURIOS_URL: https://maven.theillusivec4.top/top/theillusivec4/curios/curios-neoforge/9.3.1+1.21.1/curios-neoforge-9.3.1+1.21.1.jar
  PATCHOULI_URL: https://maven.blamejared.com/vazkii/patchouli/Patchouli/1.21-89-NEOFORGE-SNAPSHOT/Patchouli-1.21-89-NEOFORGE-20250206.161729-1.jar

permissions:
  contents: write

jobs:
  build-doc-exporter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./doc-exporter-mod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: gradle
          cache-dependency-path: |
            doc-exporter-mod/*.gradle*
            doc-exporter-mod/**/gradle-wrapper.properties
      - shell: bash
        run: |
          mkdir -p ~/.gradle/caches/fabric-loom/assets
      - uses: gradle/actions/setup-gradle@v3
      - name: Build mod
        run: |
          ./gradlew clean build
      - uses: actions/upload-artifact@v4
        with:
          name: doc-exporter-jar
          path: doc-exporter-mod/build/libs/*.jar
  find:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
      matrix: ${{ steps.filter.outputs.changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: json
          base: ${{ github.ref }}
          filters: |
            changed:
              - 'projects/*.json'
  build:
    runs-on: ubuntu-latest
    needs: [build-doc-exporter, find]
    if: ${{ needs.find.outputs.changed == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(needs.find.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: info
        run: |
          echo "MODULE=$(jq -c . < ${{ matrix.file }})" >> $GITHUB_OUTPUT
          echo "DIR=$(basename ${{ matrix.file }} .json)" >> $GITHUB_OUTPUT
      - run: |
          mkdir -p build/${{ steps.info.outputs.DIR }}
      - uses: actions/checkout@v4
        name: Checkout module
        with:
          repository: ${{ fromJson(steps.info.outputs.MODULE).repo }}
          ref: ${{ fromJson(steps.info.outputs.MODULE).branch }}
          path: build/${{ steps.info.outputs.DIR }}
      - name: Setup gradle
        shell: bash
        env:
          DIRECTORY: build/${{ steps.info.outputs.DIR }}
        run: |
          chmod +x $DIRECTORY/gradlew
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: gradle
          cache-dependency-path: |
            build/${{ steps.info.outputs.DIR }}/*.gradle*
            build/${{ steps.info.outputs.DIR }}/**/gradle-wrapper.properties
      - shell: bash
        run: |
          mkdir -p ~/.gradle/caches/fabric-loom/assets
      - uses: gradle/actions/setup-gradle@v3
      - name: retry action
        uses: Wandalen/wretry.action@v3.5.0
        with:
          attempt_limit: 3
          attempt_delay: 2000
          current_path: build/${{ steps.info.outputs.DIR }}
          command: ./gradlew clean runData build
      - name: Create mods folder
        run: |
          mkdir -p run/mods
      - name: Download Ars Nouveau
        run: |
          [ "${{ steps.info.outputs.DIR }}" -eq "ars_nouveau" ] && exit 0
          cd run/mods
          curl -LO "${{ env.ARS_URL }}"
      - name: Download Curios
        run: |
          cd run/mods
          curl -LO "${{ env.CURIOS_URL }}"
      - name: Download Patchouli
        run: |
          cd run/mods
          curl -LO "${{ env.PATCHOULI_URL }}"
      - name: Stage mod for test client
        run: |
          cp build/${{ steps.info.outputs.DIR }}/build/libs/*.jar run/mods
      - name: Download doc-exporter jar to mods folder
        uses: actions/download-artifact@v4
        with:
          name: doc-exporter-jar
          path: run/mods
      - name: Run MC test client
        uses: headlesshq/mc-runtime-test@3.0.0
        with:
          mc: 1.21.1
          modloader: neoforge
          regex: .*neoforge.*
          mc-runtime-test: neoforge
          java: ${{ env.JAVA_VERSION }}
      - name: Mark Resources Outdated
        if: failure()
        shell: bash
        run: |
          mkdir -p resources/${{ steps.info.outputs.DIR }}
          echo ${{ fromJson(steps.info.outputs.MODULE).hash }} > resources/${{ steps.info.outputs.DIR }}/.outdated
          mkdir -p wiki/${{ steps.info.outputs.DIR }}
          echo ${{ fromJson(steps.info.outputs.MODULE).hash }} > wiki/${{ steps.info.outputs.DIR }}/.outdated
      - name: Action - rsync
        if: success()
        uses: up9cloud/action-rsync@v1.4
        env:
          MODE: local
          SOURCE: "build/${{ steps.info.outputs.DIR }}/src/main/resources/ build/${{ steps.info.outputs.DIR }}/src/generated/ wiki"
          TARGET: resources/${{ steps.info.outputs.DIR }}
          VERBOSE: true
          PRE_SCRIPT: |
            rm -rf resources/${{ steps.info.outputs.DIR }}
            echo start at:
            date -u
          POST_SCRIPT: "echo done at: && date -u"
      - uses: Jarva/git-commit-push@main
        if: success() || failure()
        with:
          pull: true
          commit_message: "feat: update ${{ matrix.file }} to ${{ fromJson(steps.info.outputs.MODULE).hash }}"
