name: Sync Addons

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Sync Projects
      run: |
        ./scripts/sync.sh
    - uses: GuillaumeFalourd/git-commit-push@v1.3
      with:
        commit_message: "ci: bump version"
