name: Sync Latest Changes

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/**'
  schedule:
    - cron: "0 0 * * *"

env:
  JAVA_VERSION: 21

permissions:
  contents: write
  actions: write

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ["1.21"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ matrix.branch }}
    - name: Sync Projects
      run: |
        ./scripts/sync.sh
    - uses: GuillaumeFalourd/git-commit-push@v1.3
      with:
        commit_message: "ci: bump versions"
    - name: Detect new commit
      id: detect_commit
      run: |
        post=$(git rev-parse HEAD)
        if [ "$post" != "${{ github.sha }}" ]; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
        else
          echo "changed=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Dispatch build workflow
      if: steps.detect_commit.outputs.changed == 'true'
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh workflow run build.yml --ref ${{ matrix.branch }}
