name: Sync Addons

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ["1.20", "1.19"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ matrix.branch }}
    - name: Sync Projects
      run: |
        ./scripts/sync.sh
    - uses: Jarva/git-commit-push@main
      with:
        pull: true
        commit_message: "ci: bump versions"
